version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: codigo-app
        depends_on:
            - postgres
            - redis
        ports:
            - "8080:8080"
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/codigo_test
            SPRING_DATASOURCE_USERNAME: codigo_test
            SPRING_DATASOURCE_PASSWORD: codigo-test
            SPRING_REDIS_HOST: redis
            SPRING_REDIS_PORT: 6379
            SPRING_PROFILES_ACTIVE: docker
        networks:
            - codigo-net

    postgres:
        image: postgres:15-alpine
        container_name: codigo-postgres
        ports:
            - "5434:5432"
        environment:
            POSTGRES_DB: codigo_test
            POSTGRES_USER: codigo_test
            POSTGRES_PASSWORD: codigo-test
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - codigo-net

    redis:
        image: redis:7-alpine
        container_name: codigo-redis
        ports:
            - "6379:6379"
        networks:
            - codigo-net

networks:
    codigo-net:

volumes:
    pgdata:
