spring:
    application:
        name: codigo-code-test
    datasource:
        url: jdbc:postgresql://localhost:5434/codigo_test
        username: codigo_test
        password: codigo-test
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database-platform: org.hibernate.dialect.PostgreSQLDialect
security:
    unauthorizedUrls:
        - /auth/login
        - /auth/register
    jwt:
        token:
            expire-length: 360000000

user-pw-reset-link: http://localhost:8081/reset-pw

redis:
    expiration:
        time: 60


